import fs from "fs";
import path from "path";
import { CLIOptions } from "../cli";

function printGeneratedTS(result: string, options: CLIOptions) {
  fs.writeFileSync(path.join(options.outputDir, "index.ts"), result);
}

function printPackageJson(options: CLIOptions) {
  const pkgJson = `
  {
    "name": "${options.name}",
    "version": "${options.packageVersion}",
    "description": "This package was generated by Rapini",
    "module": "dist-esm/index.js",
    "main": "dist/index.js",
    "types": "dist/index.d.ts",
    "license": "private",
    "scripts": {
      "build": "npm run build-cjs && npm run build-esm",
      "build-cjs": "tsc index.ts --declaration --skipLibCheck --outDir dist",
      "build-esm": "tsc index.ts --skipLibCheck --moduleResolution node --target es2015 --esModuleInterop --outDir dist-esm"
    },
    "peerDependencies": {
      "axios": "0.27.x",
      "swr": "^1.3.0"
    },
    "devDependencies": {
      "@types/node": "^17.0.34",
      "typescript": "^4.6.4"
    }
  }
  `;

  fs.writeFileSync(path.join(options.outputDir, "package.json"), pkgJson);
}

export function print(result: string, options: CLIOptions) {
  if (!fs.existsSync(options.outputDir)) {
    fs.mkdirSync(options.outputDir);
  }

  printGeneratedTS(result, options);
  printPackageJson(options);
}
