import fs from "fs";

function printGeneratedTS(result: string) {
  fs.writeFileSync("./generated-package/index.ts", result);
}

function printPackageJson() {
  const pkgJson = `
  {
    "name": "generated-package",
    "version": "1.0.0",
    "description": "This package was generated by Rapini",
    "main": "dist/index.js",
    "types": "dist/index.d.ts",
    "license": "private",
    "scripts": {
      "build": "tsc index.ts --declaration --skipLibCheck --outDir dist"
    },
    "dependencies": {
      "axios": "^0.27.2",
      "react-query": "^3.39.0"
    },
    "devDependencies": {
      "@types/node": "^17.0.34",
      "typescript": "^4.6.4"
    }
  }
  `;

  fs.writeFileSync("./generated-package/package.json", pkgJson);
}

export function print(result: string) {
  if (!fs.existsSync("./generated-package")) {
    fs.mkdirSync("./generated-package");
  }

  printGeneratedTS(result);
  printPackageJson();
}
